services:
  - type: web
    name: reminder-app-backend
    env: node
    plan: free
    buildCommand: 'cd backend && npm install'
    startCommand: 'node backend/server.js'
    envVars:
      - key: MONGODB_URI
        value: 'mongodb+srv://manav:manav124@cluster0.dlwklmo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
      - key: NODE_OPTIONS
        value: '--openssl-legacy-provider'
    build:
      environment:
        NODE_VERSION: 16.x

  - type: web
    name: reminder-app-frontend
    env: static
    plan: free
    buildCommand: 'cd frontend && npm install && npm run build'
    staticPublishPath: 'frontend/build'
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html'
    build:
      environment:
        NODE_VERSION: 16.x
